### ISSUE TITLE
Can't get format from Excel, just values

### ISSUE THREAD

**Issue by adyork** [BCODMO/frictionless-usecases#5] opened 2019-04-18 18:26 UTC
We need to have the option of using the same field formatting that is in the Excel file.  The behaviour if you use "Save as" csv in Excel is to output the values with formats as they are displayed in the Excel program.  We want the same formatting shown below. **minus the extra blank columns

![image](https://user-images.githubusercontent.com/9537357/55420656-87258c00-5545-11e9-966d-9adea6d61e4e.png)

Excel "Save as"->csv gives you this:

```
Date,Treatment days,Treatment,Flume,Temperature (24h),Temperature (day),Temperature (night),Irrandiance,,,,
13-Nov,-4,344,3,27.78,28.48,27.28,NA,,,,
14-Nov,-3,344,3,27.59,27.99,27.19,34.74,,,,
15-Nov,-2,344,3,27.37,27.42,27.31,25.14,,,,
16-Nov,-1,344,3,27.47,27.76,27.18,25.03,,,,
17-Nov,1,344,3,27.67,28.10,27.24,33.26,,,,
18-Nov,2,344,3,27.61,27.88,27.33,25.23,,,,
19-Nov,3,344,3,27.68,28.10,27.26,31.65,,,,
```

This was the closest I could get when using pipelines:

```
Date,Treatment days,Treatment,Flume,Temperature (24h),Temperature (day),Temperature (night),Irrandiance
2015-11-13T00:00:00,-4,344,3,27.7810833333333,28.4814,27.2808571428571,NA
2015-11-14T00:00:00,-3,344,3,27.5885833333333,27.9920833333333,27.1850833333333,34.74306
2015-11-15T00:00:00,-2,344,3,27.3660416666667,27.4173333333333,27.31475,25.14186
2015-11-16T00:00:00,-1,344,3,27.4698333333333,27.7567916666667,27.182875,25.03278
2015-11-17T00:00:00,1,344,3,27.6653958333333,28.0955833333333,27.2352083333333,33.25788
```
* From this we would have to figure out what format was used in Excel manually and add steps in the pipeline to format/round the values back to that.
* At this point, "Date" is still a string, but it stuck in the format for DateTime not Date upon load.

using pipeline load with parameters:

```
    parameters:
      force_strings: true
      format: xlsx
      from: https://github.com/BCODMO/frictionless-usecases/blob/master/usecases/754644_Carpenter2018_physical_data/orig/Carpenter%20et%20al.%202018_data.xlsx?raw=true
      headers: 1
      name: physical
      sheet: physical data
      skip_rows: []
      validate: true
```

It would be great if the user could have an option to load with the specified formats in the excel file.  That way:

* load_with_format=True would give like "27.78"  "13-Nov"
* load_with_format=False would give the value "27.7810833333333"  and a default date format like 2015-11-13.  You can't get around that you have to have a default format in the case of date since I assume whatever encoding of dates in excel doesn't make sense outside of Excel.

This challenge does not seem unique to frictionless.  I have also incountered similar setbacks with formatting on import when using read_excel in pandas. The formatting set in Excel is not imported with the data values.  I try playing around with settings to achieve the equivalent of Excel csv export with dtypes=objects (to do something similar to force_strings=True) and parse_dates=False.  But it still requires the user to go back to the original excel file, figure out what the formatting is, and then apply it to the columns in your data frame.

**Comment by adyork** [comment] 2019-04-18 18:28
See  [usecases/754644_Carpenter2018_physical_data](usecases/754644_Carpenter2018_physical_data) for an example where the Excel has formatting that we would like to import with the values.

**Comment by adyork** [comment] 2019-04-22 18:03
Hey @lwinfree.  Do you think the ability to import format info from Excel can be added to datapackage-pipelines? 

@BCODMO/frictionlessdata-pilot-project

**Comment by lwinfree** [comment] 2019-04-23 18:09
thanks for the ping @adyork! I'll take a look at this & the rest of the issues in this repo with my team and get back to you 😃

**Comment by roll** [comment] 2019-05-27 12:12
Updating `tabulator` we can get `preserve_formatting` flag for the `load` processor:

```bash
pip install --upgrade tabulator # @1.21.0
```

```yml
  - run: load
    parameters:
      preserve_formatting: true
      force_strings: true
      format: xlsx
      from: dates.xlsx
      headers: 1
      name: dates
      sheet: physical data
      skip_rows: []
      validate: true
```

The problem is that this functionality is not implemented anywhere in the Python eco-system. I mean reading `xlsx` as it's formatted in the Excel document. I've bootstraped an implementation in `tabulator` but it's very basic at the moment (though covering this exact issue).

Going forward:
- we can implemented some automated way for converting excel formats to python strings (that could be a very time-consuming task)
- we can continue adding excel formats on-demand extending the formats library/mapping (https://github.com/frictionlessdata/tabulator-py/blob/master/tabulator/parsers/xlsx.py#L117-L128)
- maybe we will be able to find some existent implementation

**Comment by roll** [comment] 2019-05-27 12:19
cc @akariv
There is something related to Excel formatting if you're interested) Any ideas are very welcome.

**Comment by cschloer** [comment] 2019-05-27 13:31
The preserve_formatting parameter worked for the example provided here! I've added it to the UI. @adyork feel free to close this issue once you've checked it working, unless you want to keep it active for more on-demand excel formats that should be preserved.

**Comment by adyork** [comment] 2019-05-28 17:20
I can confirm, it has worked as described for the few tests I have done since we incorporated the new preserve_format. 

This is great!

@roll re: your fix using tabular and your comment that `The problem is that this functionality is not implemented anywhere in the Python eco-system`

openpyxl allows access to the formats in excel.  I have a script I used this in that I could dig up but if memory serves, each cell has a .number_format that captures format information.   Oh how I wish pandas solved this ages ago.

**Comment by roll** [comment] 2019-05-29 05:53
@adyork 
So yes, `cell.format_number` is exactly what I used for `tabulator`. What I meant that I wasn't able to find any existent implementation of a converter from Excel formats (like `d-mmm`) to Python formats (like `%d-%M). So for now, it's just a plain conversion map we need to extend for other formats.

**Comment by roll** [comment] 2019-09-27 13:53
@adyork is going to add some other formats

**Comment by cschloer** [comment] 2019-11-17 10:36
Bumping this if you get a chance @adyork . I have task for myself (https://github.com/BCODMO/laminar-web/issues/399) to add more NUMBER_FORMATS based on a generalized function in order to capture numbers with precision 0-15, but it would be useful to also get some more commonly used date formats.

**Comment by adyork** [comment] 2019-11-19 17:36
I think it is better to be able to supply the format (e.g. %d %b %Y) when you set the type rather than managing a subset of supported formats out of all possible formats that could occur.    

That being said, if that isn't an option, here is a list of the most common we encounter at BCO-DMO:
%Y-%m-%d
%Y%m%d
%y%m%d
%d/%m/%Y
%d/%m/%y
%m/%d/%Y
%m/%d/%y
%d %b %Y
%d %b %y
%b %d, %Y
%B %d, %Y

TIMES:
%H:%M
%H:%M:%S
%H%M
%H%M%S

DATETIMESwith time zone  (all these are valid ISO formats) :  
%Y-%m-%dT%H:%M%Z
%Y-%m-%dT%H:%M%z
%Y-%m-%d %H:%M%Z
%Y-%m-%d %H:%M%z
%Y-%m-%dT%H:%M%S%Z
%Y-%m-%dT%H:%M%S%z
%Y-%m-%d %H:%M%S%Z
%Y-%m-%d %H:%M%S%z

DATETIMES without time zone:
This is essentially a huge combined list of all the date and time formats possibilities combined.  Not sure it is useful to list them all.

We had started talking about format lists in this so I had some already documented:
https://github.com/BCODMO/laminar-web/issues/107

**Comment by adyork** [comment] 2019-11-19 17:40
Backtracking, this issue stems from the desire to load with "what you see is what you get" meaning what is loaded into the pipeline looks like what was shown in excel.   I don't think having a managed list of formats is going to enable that since there are so many possibilities.  

This is open for debate and is just my opinion, but if the headaches with Excel datetime are too much to deal with, what about this proposal:
* If load with preserve_format, if can't detect date|time|datetime format then import as string with the same format as shown in excel (rather than changing to ISO format).
* then user can set type on the string and can supply the real format used e.g. %d %b %Y for example.

**Comment by adyork** [comment] 2019-11-19 17:45
So backtracking to the original example in this issue.  I think we all can understand that %b-%b (13-Nov) isn't a desirable format for many reasons.  But from our perspective, that is what the PI gave us and we want to be able to import it that way THEN make changes in the pipeline when we can.

That way the provenance of the format change is captured.  And we can make decisions like keeping the original format field and adding an ISO date or whether to just convert to ISO.

**Comment by cschloer** [comment] 2019-12-16 15:37
Created a pull request here: https://github.com/frictionlessdata/tabulator-py/pull/289

**Closed** 2020-01-21 11:29 UTC
